/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sctest.scdsl.parser.antlr.internal.InternalSCDslParser;
import org.sctest.scdsl.services.SCDslGrammarAccess;

public class SCDslParser extends AbstractAntlrParser {

	@Inject
	private SCDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSCDslParser createParser(XtextTokenStream stream) {
		return new InternalSCDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SContract";
	}

	public SCDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SCDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
