/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SCDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/sctest/scdsl/parser/antlr/internal/InternalSCDsl.tokens");
	}
}
