/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SCDslUiModule extends AbstractSCDslUiModule {

	public SCDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
