/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asset Rel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sctest.scdsl.sCDsl.AssetRel#isCreate <em>Create</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.AssetRel#isRead <em>Read</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.AssetRel#isUpdate <em>Update</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.AssetRel#isDelete <em>Delete</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.AssetRel#isAll <em>All</em>}</li>
 * </ul>
 *
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel()
 * @model
 * @generated
 */
public interface AssetRel extends Relationship
{
  /**
   * Returns the value of the '<em><b>Create</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Create</em>' attribute.
   * @see #setCreate(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel_Create()
   * @model
   * @generated
   */
  boolean isCreate();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.AssetRel#isCreate <em>Create</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Create</em>' attribute.
   * @see #isCreate()
   * @generated
   */
  void setCreate(boolean value);

  /**
   * Returns the value of the '<em><b>Read</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read</em>' attribute.
   * @see #setRead(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel_Read()
   * @model
   * @generated
   */
  boolean isRead();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.AssetRel#isRead <em>Read</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read</em>' attribute.
   * @see #isRead()
   * @generated
   */
  void setRead(boolean value);

  /**
   * Returns the value of the '<em><b>Update</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update</em>' attribute.
   * @see #setUpdate(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel_Update()
   * @model
   * @generated
   */
  boolean isUpdate();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.AssetRel#isUpdate <em>Update</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update</em>' attribute.
   * @see #isUpdate()
   * @generated
   */
  void setUpdate(boolean value);

  /**
   * Returns the value of the '<em><b>Delete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete</em>' attribute.
   * @see #setDelete(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel_Delete()
   * @model
   * @generated
   */
  boolean isDelete();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.AssetRel#isDelete <em>Delete</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delete</em>' attribute.
   * @see #isDelete()
   * @generated
   */
  void setDelete(boolean value);

  /**
   * Returns the value of the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All</em>' attribute.
   * @see #setAll(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getAssetRel_All()
   * @model
   * @generated
   */
  boolean isAll();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.AssetRel#isAll <em>All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All</em>' attribute.
   * @see #isAll()
   * @generated
   */
  void setAll(boolean value);

} // AssetRel
