/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sctest.scdsl.sCDsl.Element#getName <em>Name</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Element#getList <em>List</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Element#getRelationship <em>Relationship</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Element#getCompositeelement <em>Compositeelement</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Element#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Element#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(String)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement_List()
   * @model
   * @generated
   */
  String getList();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Element#getList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #getList()
   * @generated
   */
  void setList(String value);

  /**
   * Returns the value of the '<em><b>Relationship</b></em>' containment reference list.
   * The list contents are of type {@link org.sctest.scdsl.sCDsl.Relationship}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship</em>' containment reference list.
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement_Relationship()
   * @model containment="true"
   * @generated
   */
  EList<Relationship> getRelationship();

  /**
   * Returns the value of the '<em><b>Compositeelement</b></em>' containment reference list.
   * The list contents are of type {@link org.sctest.scdsl.sCDsl.CompositeElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compositeelement</em>' containment reference list.
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement_Compositeelement()
   * @model containment="true"
   * @generated
   */
  EList<CompositeElement> getCompositeelement();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.sctest.scdsl.sCDsl.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getElement_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Element
