/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sctest.scdsl.sCDsl.Relationship#getName <em>Name</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Relationship#getFrom <em>From</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Relationship#getTo <em>To</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Relationship#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getRelationship_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Relationship#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Element)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getRelationship_From()
   * @model
   * @generated
   */
  Element getFrom();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Relationship#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Element value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Element)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getRelationship_To()
   * @model
   * @generated
   */
  Element getTo();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Relationship#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Element value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference list.
   * The list contents are of type {@link org.sctest.scdsl.sCDsl.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference list.
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getRelationship_Event()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvent();

} // Relationship
