/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.sctest.scdsl.sCDsl.SCDslFactory
 * @model kind="package"
 * @generated
 */
public interface SCDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sCDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sctest.org/scdsl/SCDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sCDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SCDslPackage eINSTANCE = org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.SContractImpl <em>SContract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.SContractImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getSContract()
   * @generated
   */
  int SCONTRACT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCONTRACT__NAME = 0;

  /**
   * The feature id for the '<em><b>Platform</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCONTRACT__PLATFORM = 1;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCONTRACT__ELEMENT = 2;

  /**
   * The number of structural features of the '<em>SContract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCONTRACT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.ElementImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__LIST = 1;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__RELATIONSHIP = 2;

  /**
   * The feature id for the '<em><b>Compositeelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__COMPOSITEELEMENT = 3;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__PARAMETERS = 4;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.CompositeElementImpl <em>Composite Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.CompositeElementImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getCompositeElement()
   * @generated
   */
  int COMPOSITE_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_ELEMENT__LIST = 1;

  /**
   * The number of structural features of the '<em>Composite Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.ParticipantImpl <em>Participant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.ParticipantImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParticipant()
   * @generated
   */
  int PARTICIPANT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__LIST = ELEMENT__LIST;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__RELATIONSHIP = ELEMENT__RELATIONSHIP;

  /**
   * The feature id for the '<em><b>Compositeelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__COMPOSITEELEMENT = ELEMENT__COMPOSITEELEMENT;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__PARAMETERS = ELEMENT__PARAMETERS;

  /**
   * The feature id for the '<em><b>Creator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT__CREATOR = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Participant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.AssetImpl <em>Asset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.AssetImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getAsset()
   * @generated
   */
  int ASSET = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__LIST = ELEMENT__LIST;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__RELATIONSHIP = ELEMENT__RELATIONSHIP;

  /**
   * The feature id for the '<em><b>Compositeelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__COMPOSITEELEMENT = ELEMENT__COMPOSITEELEMENT;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__PARAMETERS = ELEMENT__PARAMETERS;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET__TYPE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Asset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.ParameterImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 1;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__IDENTIFIER = 2;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.TransactionImpl <em>Transaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.TransactionImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTransaction()
   * @generated
   */
  int TRANSACTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__LIST = ELEMENT__LIST;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__RELATIONSHIP = ELEMENT__RELATIONSHIP;

  /**
   * The feature id for the '<em><b>Compositeelement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__COMPOSITEELEMENT = ELEMENT__COMPOSITEELEMENT;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__PARAMETERS = ELEMENT__PARAMETERS;

  /**
   * The feature id for the '<em><b>Mostrar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__MOSTRAR = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__CONDITION = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Transaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.ConditionImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 1;

  /**
   * The feature id for the '<em><b>Condition Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION_TYPE = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.RelationshipImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__NAME = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__FROM = 1;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__TO = 2;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__EVENT = 3;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.EventImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 9;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.TranRelImpl <em>Tran Rel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.TranRelImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTranRel()
   * @generated
   */
  int TRAN_REL = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL__NAME = RELATIONSHIP__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL__FROM = RELATIONSHIP__FROM;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL__TO = RELATIONSHIP__TO;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL__EVENT = RELATIONSHIP__EVENT;

  /**
   * The feature id for the '<em><b>Selected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL__SELECTED = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tran Rel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAN_REL_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.impl.AssetRelImpl <em>Asset Rel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.impl.AssetRelImpl
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getAssetRel()
   * @generated
   */
  int ASSET_REL = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__NAME = RELATIONSHIP__NAME;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__FROM = RELATIONSHIP__FROM;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__TO = RELATIONSHIP__TO;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__EVENT = RELATIONSHIP__EVENT;

  /**
   * The feature id for the '<em><b>Create</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__CREATE = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Read</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__READ = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Update</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__UPDATE = RELATIONSHIP_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Delete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__DELETE = RELATIONSHIP_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL__ALL = RELATIONSHIP_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Asset Rel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_REL_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.TargetPlatform <em>Target Platform</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.TargetPlatform
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTargetPlatform()
   * @generated
   */
  int TARGET_PLATFORM = 12;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.ParType <em>Par Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.ParType
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParType()
   * @generated
   */
  int PAR_TYPE = 13;

  /**
   * The meta object id for the '{@link org.sctest.scdsl.sCDsl.ConditionTypes <em>Condition Types</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sctest.scdsl.sCDsl.ConditionTypes
   * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getConditionTypes()
   * @generated
   */
  int CONDITION_TYPES = 14;


  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.SContract <em>SContract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SContract</em>'.
   * @see org.sctest.scdsl.sCDsl.SContract
   * @generated
   */
  EClass getSContract();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.SContract#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.SContract#getName()
   * @see #getSContract()
   * @generated
   */
  EAttribute getSContract_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.SContract#getPlatform <em>Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Platform</em>'.
   * @see org.sctest.scdsl.sCDsl.SContract#getPlatform()
   * @see #getSContract()
   * @generated
   */
  EAttribute getSContract_Platform();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.SContract#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.sctest.scdsl.sCDsl.SContract#getElement()
   * @see #getSContract()
   * @generated
   */
  EReference getSContract_Element();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.sctest.scdsl.sCDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Element#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>List</em>'.
   * @see org.sctest.scdsl.sCDsl.Element#getList()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_List();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.Element#getRelationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relationship</em>'.
   * @see org.sctest.scdsl.sCDsl.Element#getRelationship()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Relationship();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.Element#getCompositeelement <em>Compositeelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Compositeelement</em>'.
   * @see org.sctest.scdsl.sCDsl.Element#getCompositeelement()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Compositeelement();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.Element#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.sctest.scdsl.sCDsl.Element#getParameters()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Parameters();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.CompositeElement <em>Composite Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composite Element</em>'.
   * @see org.sctest.scdsl.sCDsl.CompositeElement
   * @generated
   */
  EClass getCompositeElement();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.CompositeElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.CompositeElement#getName()
   * @see #getCompositeElement()
   * @generated
   */
  EAttribute getCompositeElement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.CompositeElement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>List</em>'.
   * @see org.sctest.scdsl.sCDsl.CompositeElement#getList()
   * @see #getCompositeElement()
   * @generated
   */
  EAttribute getCompositeElement_List();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Participant <em>Participant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Participant</em>'.
   * @see org.sctest.scdsl.sCDsl.Participant
   * @generated
   */
  EClass getParticipant();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Participant#isCreator <em>Creator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Creator</em>'.
   * @see org.sctest.scdsl.sCDsl.Participant#isCreator()
   * @see #getParticipant()
   * @generated
   */
  EAttribute getParticipant_Creator();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Asset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset</em>'.
   * @see org.sctest.scdsl.sCDsl.Asset
   * @generated
   */
  EClass getAsset();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Asset#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.sctest.scdsl.sCDsl.Asset#getType()
   * @see #getAsset()
   * @generated
   */
  EAttribute getAsset_Type();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.sctest.scdsl.sCDsl.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.sctest.scdsl.sCDsl.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Type();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Parameter#isIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.sctest.scdsl.sCDsl.Parameter#isIdentifier()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Identifier();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Transaction <em>Transaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transaction</em>'.
   * @see org.sctest.scdsl.sCDsl.Transaction
   * @generated
   */
  EClass getTransaction();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Transaction#isMostrar <em>Mostrar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mostrar</em>'.
   * @see org.sctest.scdsl.sCDsl.Transaction#isMostrar()
   * @see #getTransaction()
   * @generated
   */
  EAttribute getTransaction_Mostrar();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.Transaction#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Condition</em>'.
   * @see org.sctest.scdsl.sCDsl.Transaction#getCondition()
   * @see #getTransaction()
   * @generated
   */
  EReference getTransaction_Condition();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.sctest.scdsl.sCDsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.Condition#getName()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.sctest.scdsl.sCDsl.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Condition();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Condition#getConditionType <em>Condition Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition Type</em>'.
   * @see org.sctest.scdsl.sCDsl.Condition#getConditionType()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_ConditionType();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see org.sctest.scdsl.sCDsl.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Relationship#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.Relationship#getName()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_Name();

  /**
   * Returns the meta object for the reference '{@link org.sctest.scdsl.sCDsl.Relationship#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.sctest.scdsl.sCDsl.Relationship#getFrom()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_From();

  /**
   * Returns the meta object for the reference '{@link org.sctest.scdsl.sCDsl.Relationship#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.sctest.scdsl.sCDsl.Relationship#getTo()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_To();

  /**
   * Returns the meta object for the containment reference list '{@link org.sctest.scdsl.sCDsl.Relationship#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Event</em>'.
   * @see org.sctest.scdsl.sCDsl.Relationship#getEvent()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Event();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see org.sctest.scdsl.sCDsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Event#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.sctest.scdsl.sCDsl.Event#getDescription()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Description();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sctest.scdsl.sCDsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.TranRel <em>Tran Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tran Rel</em>'.
   * @see org.sctest.scdsl.sCDsl.TranRel
   * @generated
   */
  EClass getTranRel();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.TranRel#isSelected <em>Selected</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Selected</em>'.
   * @see org.sctest.scdsl.sCDsl.TranRel#isSelected()
   * @see #getTranRel()
   * @generated
   */
  EAttribute getTranRel_Selected();

  /**
   * Returns the meta object for class '{@link org.sctest.scdsl.sCDsl.AssetRel <em>Asset Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset Rel</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel
   * @generated
   */
  EClass getAssetRel();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.AssetRel#isCreate <em>Create</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Create</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel#isCreate()
   * @see #getAssetRel()
   * @generated
   */
  EAttribute getAssetRel_Create();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.AssetRel#isRead <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Read</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel#isRead()
   * @see #getAssetRel()
   * @generated
   */
  EAttribute getAssetRel_Read();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.AssetRel#isUpdate <em>Update</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Update</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel#isUpdate()
   * @see #getAssetRel()
   * @generated
   */
  EAttribute getAssetRel_Update();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.AssetRel#isDelete <em>Delete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delete</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel#isDelete()
   * @see #getAssetRel()
   * @generated
   */
  EAttribute getAssetRel_Delete();

  /**
   * Returns the meta object for the attribute '{@link org.sctest.scdsl.sCDsl.AssetRel#isAll <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>All</em>'.
   * @see org.sctest.scdsl.sCDsl.AssetRel#isAll()
   * @see #getAssetRel()
   * @generated
   */
  EAttribute getAssetRel_All();

  /**
   * Returns the meta object for enum '{@link org.sctest.scdsl.sCDsl.TargetPlatform <em>Target Platform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Target Platform</em>'.
   * @see org.sctest.scdsl.sCDsl.TargetPlatform
   * @generated
   */
  EEnum getTargetPlatform();

  /**
   * Returns the meta object for enum '{@link org.sctest.scdsl.sCDsl.ParType <em>Par Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Par Type</em>'.
   * @see org.sctest.scdsl.sCDsl.ParType
   * @generated
   */
  EEnum getParType();

  /**
   * Returns the meta object for enum '{@link org.sctest.scdsl.sCDsl.ConditionTypes <em>Condition Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Condition Types</em>'.
   * @see org.sctest.scdsl.sCDsl.ConditionTypes
   * @generated
   */
  EEnum getConditionTypes();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SCDslFactory getSCDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.SContractImpl <em>SContract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.SContractImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getSContract()
     * @generated
     */
    EClass SCONTRACT = eINSTANCE.getSContract();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCONTRACT__NAME = eINSTANCE.getSContract_Name();

    /**
     * The meta object literal for the '<em><b>Platform</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCONTRACT__PLATFORM = eINSTANCE.getSContract_Platform();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCONTRACT__ELEMENT = eINSTANCE.getSContract_Element();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.ElementImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__LIST = eINSTANCE.getElement_List();

    /**
     * The meta object literal for the '<em><b>Relationship</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__RELATIONSHIP = eINSTANCE.getElement_Relationship();

    /**
     * The meta object literal for the '<em><b>Compositeelement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__COMPOSITEELEMENT = eINSTANCE.getElement_Compositeelement();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__PARAMETERS = eINSTANCE.getElement_Parameters();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.CompositeElementImpl <em>Composite Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.CompositeElementImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getCompositeElement()
     * @generated
     */
    EClass COMPOSITE_ELEMENT = eINSTANCE.getCompositeElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSITE_ELEMENT__NAME = eINSTANCE.getCompositeElement_Name();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSITE_ELEMENT__LIST = eINSTANCE.getCompositeElement_List();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.ParticipantImpl <em>Participant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.ParticipantImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParticipant()
     * @generated
     */
    EClass PARTICIPANT = eINSTANCE.getParticipant();

    /**
     * The meta object literal for the '<em><b>Creator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANT__CREATOR = eINSTANCE.getParticipant_Creator();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.AssetImpl <em>Asset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.AssetImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getAsset()
     * @generated
     */
    EClass ASSET = eINSTANCE.getAsset();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET__TYPE = eINSTANCE.getAsset_Type();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.ParameterImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__IDENTIFIER = eINSTANCE.getParameter_Identifier();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.TransactionImpl <em>Transaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.TransactionImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTransaction()
     * @generated
     */
    EClass TRANSACTION = eINSTANCE.getTransaction();

    /**
     * The meta object literal for the '<em><b>Mostrar</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSACTION__MOSTRAR = eINSTANCE.getTransaction_Mostrar();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSACTION__CONDITION = eINSTANCE.getTransaction_Condition();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.ConditionImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCondition_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '<em><b>Condition Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION_TYPE = eINSTANCE.getCondition_ConditionType();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.RelationshipImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__NAME = eINSTANCE.getRelationship_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__FROM = eINSTANCE.getRelationship_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__TO = eINSTANCE.getRelationship_To();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__EVENT = eINSTANCE.getRelationship_Event();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.EventImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DESCRIPTION = eINSTANCE.getEvent_Description();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.TranRelImpl <em>Tran Rel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.TranRelImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTranRel()
     * @generated
     */
    EClass TRAN_REL = eINSTANCE.getTranRel();

    /**
     * The meta object literal for the '<em><b>Selected</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAN_REL__SELECTED = eINSTANCE.getTranRel_Selected();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.impl.AssetRelImpl <em>Asset Rel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.impl.AssetRelImpl
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getAssetRel()
     * @generated
     */
    EClass ASSET_REL = eINSTANCE.getAssetRel();

    /**
     * The meta object literal for the '<em><b>Create</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_REL__CREATE = eINSTANCE.getAssetRel_Create();

    /**
     * The meta object literal for the '<em><b>Read</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_REL__READ = eINSTANCE.getAssetRel_Read();

    /**
     * The meta object literal for the '<em><b>Update</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_REL__UPDATE = eINSTANCE.getAssetRel_Update();

    /**
     * The meta object literal for the '<em><b>Delete</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_REL__DELETE = eINSTANCE.getAssetRel_Delete();

    /**
     * The meta object literal for the '<em><b>All</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSET_REL__ALL = eINSTANCE.getAssetRel_All();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.TargetPlatform <em>Target Platform</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.TargetPlatform
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getTargetPlatform()
     * @generated
     */
    EEnum TARGET_PLATFORM = eINSTANCE.getTargetPlatform();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.ParType <em>Par Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.ParType
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getParType()
     * @generated
     */
    EEnum PAR_TYPE = eINSTANCE.getParType();

    /**
     * The meta object literal for the '{@link org.sctest.scdsl.sCDsl.ConditionTypes <em>Condition Types</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sctest.scdsl.sCDsl.ConditionTypes
     * @see org.sctest.scdsl.sCDsl.impl.SCDslPackageImpl#getConditionTypes()
     * @generated
     */
    EEnum CONDITION_TYPES = eINSTANCE.getConditionTypes();

  }

} //SCDslPackage
