/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Target Platform</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTargetPlatform()
 * @model
 * @generated
 */
public enum TargetPlatform implements Enumerator
{
  /**
   * The '<em><b>IBM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IBM_VALUE
   * @generated
   * @ordered
   */
  IBM(0, "IBM", "IBM"),

  /**
   * The '<em><b>Azure</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AZURE_VALUE
   * @generated
   * @ordered
   */
  AZURE(1, "Azure", "Azure"),

  /**
   * The '<em><b>Solidity</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SOLIDITY_VALUE
   * @generated
   * @ordered
   */
  SOLIDITY(2, "Solidity", "Solidity");

  /**
   * The '<em><b>IBM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IBM
   * @model
   * @generated
   * @ordered
   */
  public static final int IBM_VALUE = 0;

  /**
   * The '<em><b>Azure</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AZURE
   * @model name="Azure"
   * @generated
   * @ordered
   */
  public static final int AZURE_VALUE = 1;

  /**
   * The '<em><b>Solidity</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SOLIDITY
   * @model name="Solidity"
   * @generated
   * @ordered
   */
  public static final int SOLIDITY_VALUE = 2;

  /**
   * An array of all the '<em><b>Target Platform</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TargetPlatform[] VALUES_ARRAY =
    new TargetPlatform[]
    {
      IBM,
      AZURE,
      SOLIDITY,
    };

  /**
   * A public read-only list of all the '<em><b>Target Platform</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TargetPlatform> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Target Platform</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TargetPlatform get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TargetPlatform result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Target Platform</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TargetPlatform getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TargetPlatform result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Target Platform</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TargetPlatform get(int value)
  {
    switch (value)
    {
      case IBM_VALUE: return IBM;
      case AZURE_VALUE: return AZURE;
      case SOLIDITY_VALUE: return SOLIDITY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TargetPlatform(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TargetPlatform
