/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tran Rel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sctest.scdsl.sCDsl.TranRel#isSelected <em>Selected</em>}</li>
 * </ul>
 *
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTranRel()
 * @model
 * @generated
 */
public interface TranRel extends Relationship
{
  /**
   * Returns the value of the '<em><b>Selected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected</em>' attribute.
   * @see #setSelected(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTranRel_Selected()
   * @model
   * @generated
   */
  boolean isSelected();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.TranRel#isSelected <em>Selected</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected</em>' attribute.
   * @see #isSelected()
   * @generated
   */
  void setSelected(boolean value);

} // TranRel
