/**
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.sCDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sctest.scdsl.sCDsl.Transaction#isMostrar <em>Mostrar</em>}</li>
 *   <li>{@link org.sctest.scdsl.sCDsl.Transaction#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTransaction()
 * @model
 * @generated
 */
public interface Transaction extends Element
{
  /**
   * Returns the value of the '<em><b>Mostrar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mostrar</em>' attribute.
   * @see #setMostrar(boolean)
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTransaction_Mostrar()
   * @model
   * @generated
   */
  boolean isMostrar();

  /**
   * Sets the value of the '{@link org.sctest.scdsl.sCDsl.Transaction#isMostrar <em>Mostrar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mostrar</em>' attribute.
   * @see #isMostrar()
   * @generated
   */
  void setMostrar(boolean value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference list.
   * The list contents are of type {@link org.sctest.scdsl.sCDsl.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference list.
   * @see org.sctest.scdsl.sCDsl.SCDslPackage#getTransaction_Condition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getCondition();

} // Transaction
