/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSCDslScopeProvider extends DelegatingScopeProvider {
}
