/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SCDslStandaloneSetup extends SCDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SCDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
