/*
 * generated by Xtext 2.22.0
 */
package org.sctest.scdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.scdsl.ui.internal.ScdslActivator;

public class SCDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ScdslActivator.getInstance().getInjector("org.sctest.scdsl.SCDsl");
	}

}
